import {
  Star,
  CheckSquare,
  Type,
  Mail,
  Phone,
  ImageIcon,
  ToggleLeft,
  MessageSquare,
  BarChart3,
  Calendar,
  CreditCard,
  List,
  Link,
  Camera,
  Users,
  Hash,
  Grid3X3,
  ArrowUpDown,
  ChevronDown,
  FileCheck,
  Thermometer,
  ThumbsUp,
  Home,
  Divide,
} from "lucide-react"

export const questionTypes = {
  frequentlyUsed: [
    { name: "Opinion Scale", icon: BarChart3, description: "1-10 rating scale" },
    { name: "Multiple Choice", icon: CheckSquare, description: "Select one or more options" },
    { name: "Text", icon: Type, description: "Short or long text input" },
    { name: "Email", icon: Mail, description: "Email address input" },
    { name: "Phone Number", icon: Phone, description: "Phone number input" },
    { name: "Rating", icon: Star, description: "Star rating system" },
    { name: "Contact Form", icon: FileCheck, description: "Complete contact information" },
  ],
  otherQuestions: [
    { name: "Picture Choice", icon: ImageIcon, description: "Choose from images" },
    { name: "Yes or No", icon: ToggleLeft, description: "Binary choice question" },
    { name: "Message", icon: MessageSquare, description: "Display text message" },
    { name: "Upload", icon: FileCheck, description: "File upload field" },
    { name: "Bipolar Matrix", icon: Grid3X3, description: "Matrix with opposing scales" },
    { name: "Slider", icon: Thermometer, description: "Sliding scale input" },
    { name: "Date", icon: Calendar, description: "Date picker" },
    { name: "Payment", icon: CreditCard, description: "Payment processing" },
    { name: "Group Rank", icon: List, description: "Rank items in order" },
    { name: "Constant Sum", icon: Hash, description: "Distribute points" },
    { name: "Website", icon: Link, description: "Website URL input" },
    { name: "Signature", icon: FileCheck, description: "Digital signature" },
    { name: "Photo Capture", icon: Camera, description: "Take photo with camera" },
    { name: "Group Rating", icon: Users, description: "Rate multiple items" },
    { name: "Number", icon: Hash, description: "Numeric input" },
    { name: "Matrix", icon: Grid3X3, description: "Grid of questions" },
    { name: "Rank Order", icon: ArrowUpDown, description: "Drag to reorder" },
    { name: "Dropdown", icon: ChevronDown, description: "Select from dropdown" },
    { name: "Consent/Agreement", icon: FileCheck, description: "Terms agreement" },
    { name: "Heatmap", icon: Thermometer, description: "Click heatmap" },
  ],
  otherElements: [
    { name: "Thank You Page", icon: ThumbsUp, description: "End survey message" },
    { name: "Welcome Page", icon: Home, description: "Survey introduction" },
    { name: "Section", icon: Divide, description: "Organize questions" },
    { name: "Authenticator", icon: FileCheck, description: "User verification", isNew: true },
  ],
}
